### ISSUE TITLE
Allow Substitutions in pypyr.steps.pype

### ISSUE THREAD

**Issue by rickardcronholm** [pypyr/pypyr-cli#76]
Allow Substitutions in pype steps.
Rationale; Just like having the possibility to have Run/Skip being evaluated at runtime it could be useful to have be able to pick the pipe to run at runtime.

A toy example is that an initial step is to classify an object into a shape (square, circle, hexagon). That could be followed by a pipe that computes data (area etc) for that shape. Back in the parent pipe a report can be conducted regardless of which child pipe generated the data.

**Comment by 345thomas** [comment]
This is an awesome idea! ❤️ Sweeeeet!

Might as well do it for all the args too!
  name: 'pipeline name' # mandatory. string.
  pipeArg: 'argument here' # optional. string.
  raiseError: True # optional. bool. Defaults True.
  skipParse: True # optional. bool. Defaults True.
  useParentContext: True  # optional. bool. Defaults True.

Are you planning to do this one, Rickard?

**Comment by 345thomas** [comment]
wow, an IT timeline that's planning for next year, not yesterday! 😄 Thanks for setting out the timeline like that, really helps with prioritization! I'm pretty excited about this one, it will open up all sorts of great new possibilities for pypyr, so wonderful idea thank you!

So you know, it's actually not all that big a change (the unit tests will actually be the bulk of the effort). The functional change will be something like this:

Amend `def get_arguments(context)` in `./steps/pype.py` to something like this:
```
    return (context.get_formatted_string(pipeline_name),
            context.get_formatted_as_type(use_parent_context, out_type=bool),
            pipe_arg if pipe_arg is None else context.get_formatted_string(pipe_arg),
            context.get_formatted_as_type(skip_parse, out_type=bool),
            context.get_formatted_as_type(raise_error, out_type=bool))
```

**Comment by rickardcronholm** [comment]
I may have credited the IT dep a little too much here. That is when I predict the IT dep will come shouting that it should be implemented yesterday :unamused: 
I'm quite aware that it is not very code intensive apart from the unittests. The tests are typically what's taking the longest for me, which indicates that I probably should write them. 

If you are ok with a slow paced development and some hand holding through tests I would be happy to have a go at it.

**Comment by 345thomas** [comment]
> I may have credited the IT dep a little too much here. That is when I predict the IT dep will come shouting that it should be implemented yesterday

😂 that's some good predictive insight there, Nostradamus!

I'm not in a particular rush, so if you'd like the opportunity to practice some testing you're more than welcome! Hit me up on discord if you'd like me to talk you through anything a bit more interactively.

The requisite unit tests will be added to `/tests/unit/pypyr/steps/pype_test.py`, the `get_arguments` section - the test coverage is already 100% per usual pypyr practice. Off the top of my head, the following will be needed:
- amend `test_pype_get_arguments_all` - likely to fail post-change because the strings will be cast to bools
- add `test_pype_get_arguments_substitutions` - pretty much copy the  `test_pype_get_arguments_all` function, but make input values string interpolations. e.g
```
    context = Context({
	trueValue: True,
	falseValue: False,
	arbString: blah,
        'pype': {
            'name': 'pipe {arbString} name',
            'pipeArg': '{arbString}',
            'useParentContext': '{falseValue}',
            'skipParse': '{falseValue}',
            'raiseError': '{falseValue}'
        }
    })
```
- add test where pipeArg input is None to make sure the if branch `if pipe_arg is None` on assignment is tested
- add test where string interpolation parsing fails. use `test_pype_get_arguments_name_empty` or similar as example of how to catch expected exceptions.
- add test where `'name': '{arbString}',` results in `name: None`. You're probably going to want to code defensively for that in `pype.py` with a `if not pipeline_name: `, to raise a sensible exception - like maybe `pypyr.errors.KeyInContextHasNoValueError`. You're prob going to want to do the pipeline_name string interpolation further up after the check that pype['name'] is not None, rather than just on the return tuple as the rest.
- add test where `'name': '{arbString}',` results in `name: ''`
- add test to confirm how unexpected types resolve to bools - e.g 
```
   falseValue`: 'thisisastring`, 
   trueValue: 1, 
   trueString: 'True'
```
